version: "{build}"
clone_depth: 1
image: Ubuntu2204

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install libx11-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev
- sh: sudo apt-get -y install libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
- sh: ./curl_linux.sh
- sh: ./discord_linux.sh
- sh: ./freetype_linux.sh
- sh: ./glad_linux.sh
- sh: ./glfw_linux.sh
- sh: ./luau_linux.sh
- sh: ./openal_linux.sh
- sh: ./yoga_linux.sh
- sh: ./zstd_linux.sh

artifacts:
- path: build
  name: libs_linux
