version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl1-mesa-dev libxkbcommon-dev libgl-dev libasound2-dev libpulse-dev
- sh: ./curl_linux.sh
- sh: ./freetype_linux.sh
- sh: ./openal_linux.sh
# - sh: ./librocket_linux.sh
- sh: ./sdl_linux.sh
- sh: ./zlib_linux.sh
- sh: ./zstd_linux.sh

artifacts:
- path: build
  name: libs_linux
