version: "{build}"
clone_depth: 1

build_script:
- cmd: call "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd" /x64
- cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" x86_amd64
# - cmd: angelscript_windows.bat
# - cmd: curl_windows.bat
# - cmd: freetype_windows.bat
- cmd: librocket_windows.bat
# - cmd: openal_windows.bat
# - cmd: sdl_windows.bat
# - cmd: zlib_windows.bat
# - cmd: zstd_windows.bat

artifacts:
- path: build
  name: libs_windows
