version: "{build}"
clone_depth: 1
image: Ubuntu2204

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install wget xz-utils
- sh: sudo apt-get -y install gcc-multilib make cmake
- sh: sudo apt-get -y install xorg-dev libxkbcommon-dev
- sh: sudo apt-get -y install libwayland-dev wayland-protocols
- sh: ./curl_linux.sh
- sh: ./discord_linux.sh
- sh: ./freetype_linux.sh
- sh: ./glad_linux.sh
- sh: ./glfw_linux.sh
- sh: ./luau_linux.sh
- sh: ./openal_linux.sh
- sh: ./yoga_linux.sh
- sh: ./zstd_linux.sh

artifacts:
- path: build
  name: libs_linux
